
"""
llm_engine.py
=============
Local Large Language Model driver utilizing Apple MLX.

This module loads the quantized Llama-3-8B model directly into the M4's 
unified memory space. It is designed as a Singleton to prevent duplicate 
RAM allocation.

We use a streaming generator (yield) so that FastAPI can pipe tokens to the 
frontend character-by-character, dramatically improving perceived latency 
for the end-user (Time-To-First-Token).
"""

import logging
from mlx_lm import load, stream_generate

logger = logging.getLogger(__name__)

class LLMEngine:
    def __init__(self, model_name: str = "mlx-community/Meta-Llama-3-8B-Instruct-4bit"):
        """
        Loads the model and tokenizer into unified memory.
        Warning: This blocks the thread for ~10-15 seconds during startup
        and consumes ~4.5GB of RAM.
        """
        logger.info(f"Loading MLX model into unified memory: {model_name}")
        try:
            # load() automatically detects and uses the Apple Silicon GPU
            self.model, self.tokenizer = load(model_name)
            logger.info("LLM successfully loaded into memory.")
        except Exception as e:
            logger.error(f"Failed to load MLX model. Error: {e}")
            raise RuntimeError(f"MLX Load failure: {e}")

    def generate_response_stream(self, prompt: str, max_tokens: int = 300):
        """
        A synchronous generator that yields text tokens as they are produced.
        
        Parameters
        ----------
        prompt : str
            The fully formatted prompt (System + Context + User query).
        max_tokens : int
            Hard cap on generation length to prevent infinite loops.
            
        Yields
        ------
        str
            The individual string tokens generated by the LLM.
        """
        logger.debug(f"Starting generation for prompt of length {len(prompt)}")
        
        # stream_generate yields chunks of text sequentially
        for response in stream_generate(
                    self.model, 
                    self.tokenizer, 
                    prompt=prompt, 
                    max_tokens=max_tokens
                ):
                    yield response.text  